### ISSUE TITLE
Project : Install open-source operating system to my phone

### ISSUE THREAD

**Issue by WaKeMaTTa** [WaKeMaTTa/wakematta.github.io#1]
I have a _Motorola Moto G (gen. 2)_ laying around, and I thought it would be nice to install an open-source operating system on that phone that I never use anymore.

## Tasks

- [x] Choose one open-source smartphone operating system.
- [ ] Install and configure [LineageOS].
- [ ] Install the Apps that you use frequently. Try to use less Google Servicies, if you are able.
- [ ] 3 months test period
- [ ] Conclusion (performance, limitations, feels good?, complains, ...)

## Progress notes

I choose to give a try [LineageOS].

[LineageOS]: https://lineageos.org
