### ISSUE TITLE
Project : Personal website

### ISSUE THREAD

**Issue by WaKeMaTTa** [WaKeMaTTa/wakematta.github.io#2]
I want to create a **personal website** to have a centralized place, where I can posts and recall stuff that I'm interested.

## Tasks

- [ ] Reform [wakematta.github.io] to use Jekyll + Tailwind. (use `docs/` folder!)
- [ ] Sections: web development, spirituality and personal development, cooking an recipes.
- [ ] Add link to my [trakt.tv] page.

## Progress notes

...

[wakematta.github.io]: https://wakematta.github.io/
[trakt.tv]: https://trakt.tv/
