### ISSUE TITLE
Project : Raspberry Pi in to VPN and Ad Blocking

### ISSUE THREAD

**Issue by WaKeMaTTa** [WaKeMaTTa/wakematta.github.io#3]
I want to build my own Raspberry Pi VPN + Tracking Blocking + Ad Blocking.

## Tasks

- [ ] Buy Raspberry Pi 4B
- [ ] Read posts and watch videos about this subject.
- [ ] Build your own.
- [ ] 3 months test period
- [ ] Conclusion (performance, limitations, feels good?, complains, ...)

## Progress notes

I found a few good posts that exaplains in detaill how to do it:

- https://blog.arturofm.com/pi-hole-with-raspberry-pi-setup-2020/
- https://blog.arturofm.com/setup-vpn-server-with-ad-blocker-using-raspberry-pi/
- https://jttyeung.github.io/2017/06/01/raspberry-pi-vpn-setup.html
